### ISSUE TITLE
pygame is required for pendulum demo in chap01

### ISSUE THREAD

**Issue by sepilqi** [maxpumperla/learning_ray#4]
`ModuleNotFoundError: No module named 'pygame'`

[location](https://learning.oreilly.com/library/view/learning-ray/9781098117214/ch01.html#:-:text=rllib%20train%20-f%20pendulum.yml)

details

```bash
rllib train -f pendulum.yml
2022-10-18 17:10:38,085 INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 172.24.16.114:6379...
2022-10-18 17:10:38,091 INFO worker.py:1509 -- Connected to Ray cluster. View the dashboard at 127.0.0.1:8265
/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/util/placement_group.py:78: DeprecationWarning: placement_group parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrategy(...) instead, see the usage at https://docs.ray.io/en/releases-2.0.0/ray-core/package-ref.html#ray-remote.
  return bundle_reservation_check.options(
/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/_private/ray_option_utils.py:266: DeprecationWarning: Setting 'object_store_memory' for actors is deprecated since it doesn't actually reserve the required object store memory. Use object spilling that's enabled by default (https://docs.ray.io/en/releases-2.0.0/ray-core/objects/object-spilling.html) instead to bypass the object store memory size limitation.
  warnings.warn(
/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrategy(...) instead, see the usage at https://docs.ray.io/en/releases-2.0.0/ray-core/package-ref.html#ray-remote.
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group_bundle_index parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrategy(...) instead, see the usage at https://docs.ray.io/en/releases-2.0.0/ray-core/package-ref.html#ray-remote.
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/actor.py:637: DeprecationWarning: placement_group_capture_child_tasks parameter is deprecated. Use scheduling_strategy=PlacementGroupSchedulingStrategy(...) instead, see the usage at https://docs.ray.io/en/releases-2.0.0/ray-core/package-ref.html#ray-remote.
  return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
(PPO pid=52305) 2022-10-18 17:10:42,722 INFO algorithm.py:1871 -- Your framework setting is 'tf', meaning you are using static-graph mode. Set framework='tf2' to enable eager execution with tf2.x. You may also then want to set eager_tracing=True in order to reach similar execution speed as with static-graph mode.
(PPO pid=52305) 2022-10-18 17:10:42,722 INFO ppo.py:378 -- In multi-agent mode, policies will be optimized sequentray::PPO.__init__() (pid=52305, ip=172.24.16.114, repr=PPO)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
ModuleNotFoundError: No module named 'pygame'

(PPO pid=52305)     cls = load(self.entry_point)
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 55, in load
(PPO pid=52305)     mod = importlib.import_module(mod_name)
(PPO pid=52305)   File "/root/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
(PPO pid=52305)     return _bootstrap._gcd_import(name[level:], package, level)
(PPO pid=52305)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
(PPO pid=52305)   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
(PPO pid=52305)   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
(PPO pid=52305)   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
(PPO pid=52305)   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
(PPO pid=52305)   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
(PPO pid=52305)     from gym.envs.classic_control.cartpole import CartPoleEnv
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
(PPO pid=52305)     import pygame
(PPO pid=52305) ModuleNotFoundError: No module named 'pygame'
(PPO pid=52305)
(PPO pid=52305) During handling of the above exception, another exception occurred:
(PPO pid=52305)
(PPO pid=52305) ray::PPO.__init__() (pid=52305, ip=172.24.16.114, repr=PPO)
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
(PPO pid=52305)     super().__init__(config=config, logger_creator=logger_creator, **kwargs)
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
(PPO pid=52305)     self.setup(copy.deepcopy(self.config))
(PPO pid=52305)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
(PPO pid=52305)     raise e.args[0].args[2]
(PPO pid=52305) ModuleNotFoundError: No module named 'pygame'
(RolloutWorker pid=52448) 2022-10-18 17:10:46,627       ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=52448, ip=172.24.16.114, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7edf6bb79250>)
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
(RolloutWorker pid=52448)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/env/utils.py", line 50, in _gym_env_creator
(RolloutWorker pid=52448)     return gym.make(env_descriptor, **env_context)
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
== Status ==
Current time: 2022-10-18 17:10:46 (running for 00:00:08.53)
Memory usage on this node: 275.2/502.1 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/64 CPUs, 0/0 GPUs, 0.0/254.8 GiB heap, 0.0/113.19 GiB objects
Result logdir: /root/ray_results/pendulumppo
Number of trials: 1/1 (1 ERROR)
Number of errored trials: 1
+-----------------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                |
|-----------------------------+--------------+-------------------------------------------------------------------------------------------|
| PPO_Pendulum-v1_bb4a6_00000 |            1 | /root/ray_results/pendulumppo/PPO_Pendulum-v1_bb4a6_00000_0_2022-10-18_17-10-38/error.txt |
+-----------------------------+--------------+-------------------------------------------------------------------------------------------+
(RolloutWorker pid=52448)     return registry.make(id, **kwargs)

(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
(RolloutWorker pid=52448)     return spec.make(**kwargs)
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 139, in make
(RolloutWorker pid=52448)     cls = load(self.entry_point)
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 55, in load
(RolloutWorker pid=52448)     mod = importlib.import_module(mod_name)
(RolloutWorker pid=52448)   File "/root/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
(RolloutWorker pid=52448)     return _bootstrap._gcd_import(name[level:], package, level)
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
(RolloutWorker pid=52448)   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
(RolloutWorker pid=52448)     from gym.envs.classic_control.cartpole import CartPoleEnv
(RolloutWorker pid=52448)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
(RolloutWorker pid=52448)     import pygame
(RolloutWorker pid=52448) ModuleNotFoundError: No module named 'pygame'
(RolloutWorker pid=52447) 2022-10-18 17:10:46,644       ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=52447, ip=172.24.16.114, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fcf394a5280>)
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
(RolloutWorker pid=52447)     self.env = env_creator(copy.deepcopy(self.env_context))
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/env/utils.py", line 50, in _gym_env_creator
(RolloutWorker pid=52447)     return gym.make(env_descriptor, **env_context)
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
(RolloutWorker pid=52447)     return registry.make(id, **kwargs)
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
(RolloutWorker pid=52447)     return spec.make(**kwargs)
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 139, in make
(RolloutWorker pid=52447)     cls = load(self.entry_point)
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 55, in load
(RolloutWorker pid=52447)     mod = importlib.import_module(mod_name)
(RolloutWorker pid=52447)   File "/root/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
(RolloutWorker pid=52447)     return _bootstrap._gcd_import(name[level:], package, level)
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
(RolloutWorker pid=52447)   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
(RolloutWorker pid=52447)     from gym.envs.classic_control.cartpole import CartPoleEnv
(RolloutWorker pid=52447)   File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
(RolloutWorker pid=52447)     import pygame
(RolloutWorker pid=52447) ModuleNotFoundError: No module named 'pygame'
== Status ==
Current time: 2022-10-18 17:10:46 (running for 00:00:08.53)
Memory usage on this node: 275.2/502.1 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/64 CPUs, 0/0 GPUs, 0.0/254.8 GiB heap, 0.0/113.19 GiB objects
Result logdir: /root/ray_results/pendulumppo
Number of trials: 1/1 (1 ERROR)
Number of errored trials: 1
+-----------------------------+--------------+-------------------------------------------------------------------------------------------+
| Trial name                  |   # failures | error file                                                                                |
|-----------------------------+--------------+-------------------------------------------------------------------------------------------|
| PPO_Pendulum-v1_bb4a6_00000 |            1 | /root/ray_results/pendulumppo/PPO_Pendulum-v1_bb4a6_00000_0_2022-10-18_17-10-38/error.txt |
+-----------------------------+--------------+-------------------------------------------------------------------------------------------+

2022-10-18 17:10:46,656 ERROR ray_trial_executor.py:103 -- An exception occurred when trying to stop the Ray actor:Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/execution/ray_trial_executor.py", line 94, in _post_stop_cleanup
    ray.get(future, timeout=0)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=52305, ip=172.24.16.114, repr=PPO)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 125, in __init__
    self.add_workers(
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 391, in foreach_worker
    remote_results = ray.get([w.apply.remote(func) for w in self.remote_workers()])
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::RolloutWorker.__init__() (pid=52448, ip=172.24.16.114, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7edf6bb79250>)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 490, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/env/utils.py", line 50, in _gym_env_creator
    return gym.make(env_descriptor, **env_context)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 139, in make
    cls = load(self.entry_point)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/registration.py", line 55, in load
    mod = importlib.import_module(mod_name)
  File "/root/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py", line 1, in <module>
    from gym.envs.classic_control.cartpole import CartPoleEnv
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py", line 10, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

During handling of the above exception, another exception occurred:

ray::PPO.__init__() (pid=52305, ip=172.24.16.114, repr=PPO)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 308, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 157, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 443, in setup
    raise e.args[0].args[2]
ModuleNotFoundError: No module named 'pygame'

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/bin/rllib", line 8, in <module>
    sys.exit(cli())
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/scripts.py", line 41, in cli
    train.run(options, train_parser)
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/rllib/train.py", line 269, in run
    run_experiments(
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/tune.py", line 848, in run_experiments
    return run(
  File "/root/.cache/pypoetry/virtualenvs/ray-KeD1w6JO-py3.9/lib/python3.9/site-packages/ray/tune/tune.py", line 752, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_Pendulum-v1_bb4a6_00000])
```

**Comment by sepilqi** [comment]
share my runnable `requiremnets.txt`

```bash
absl-py==1.2.0
aiohttp==3.8.3
aiohttp-cors==0.7.0
aiorwlock==1.3.0
aiosignal==1.2.0
anyio==3.6.1
asgiref==3.5.2
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.1.0
backoff==1.10.0
blessed==1.19.1
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.0.4
cloudpickle==2.2.0
colorful==0.5.4
contourpy==1.0.5
cycler==0.11.0
distlib==0.3.6
fonttools==4.37.4
frozenlist==1.3.1
fsspec==2022.8.2
gast==0.4.0
google-api-core==2.10.2
google-auth==2.12.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.56.4
gpustat==1.0.0
grpcio==1.43.0
gym==0.23.1
gym-notices==0.0.8
h11==0.14.0
h5py==3.7.0
idna==3.4
imageio==2.22.1
importlib-metadata==5.0.0
iso8601==1.1.0
jsonschema==4.16.0
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
kopf==1.35.6
kubernetes==24.2.0
libclang==14.0.6
lz4==4.0.2
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.0
msgpack==1.0.4
multidict==6.0.2
networkx==2.8.7
numpy==1.23.3
nvidia-ml-py==11.495.46
oauthlib==3.2.1
opencensus==0.11.0
opencensus-context==0.1.3
opentelemetry-api==1.1.0
opentelemetry-exporter-otlp==1.1.0
opentelemetry-exporter-otlp-proto-grpc==1.1.0
opentelemetry-proto==1.1.0
opentelemetry-sdk==1.1.0
opentelemetry-semantic-conventions==0.20b0
opt-einsum==3.3.0
packaging==21.3
pandas==1.5.0
Pillow==9.2.0
platformdirs==2.5.2
prometheus-client==0.13.1
protobuf==3.19.6
psutil==5.9.2
py-spy==0.3.14
pyarrow==6.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.10.2
pygame==2.1.2
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.4
PyWavelets==1.4.1
PyYAML==6.0
ray==2.0.0
ray-cpp==2.0.0
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-image==0.19.3
scipy==1.9.1
six==1.16.0
smart-open==6.2.0
sniffio==1.3.0
starlette==0.20.4
tabulate==0.9.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorboardX==2.5.1
tensorflow==2.10.0
tensorflow-estimator==2.10.0
tensorflow-io-gcs-filesystem==0.27.0
termcolor==2.0.1
tifffile==2022.8.12
typing_extensions==4.4.0
urllib3==1.26.12
uvicorn==0.16.0
virtualenv==20.16.5
wcwidth==0.2.5
websocket-client==1.4.1
Werkzeug==2.2.2
wrapt==1.14.1
yarl==1.8.1
zipp==3.8.1
```

**Comment by maxpumperla** [comment]
@sepilqi thanks for submitting this. we're in the middle of finalising most chapters now, and the polish we do in the next month will include a full code run and dependency check for all notebooks. Apologies for the inconvenience for now, we'll get there eventually!

**Comment by sepilqi** [comment]
I am so happy to get your response, and I am reading your book these days, and it helped me a lot😁. thx for your writing, I am looking forward to finish it.
